//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoUtility.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeoUtility.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eine Typ-Konvertierung zwischen {0} und {1} ist nicht erlaubt..
        /// </summary>
        internal static string DE_ERROR_CONVERTFROM {
            get {
                return ResourceManager.GetString("DE_ERROR_CONVERTFROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechtswert außerhalb des für Deutschland definierten Gauss-Krüger-Systems: 
        ///Geogr. Länge: 5 bis 16 E..
        /// </summary>
        internal static string DE_ERROR_GAUSS_EAST {
            get {
                return ResourceManager.GetString("DE_ERROR_GAUSS_EAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hochwert außerhalb des für Deutschland definierten Gauss-Krüger-Systems: 
        ///Geogr. Breite: 46 bis 55 N..
        /// </summary>
        internal static string DE_ERROR_GAUSS_NORTH {
            get {
                return ResourceManager.GetString("DE_ERROR_GAUSS_NORTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breitengrad ungültig. Definierter Bereich: -80 (südl.) bis +84 (nördl.).
        /// </summary>
        internal static string DE_ERROR_GEO_LATITUDE {
            get {
                return ResourceManager.GetString("DE_ERROR_GEO_LATITUDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Längengrad ungültig. Definierter Bereich: -180 (westl.) bis +180 (östl.).
        /// </summary>
        internal static string DE_ERROR_GEO_LONGITUDE {
            get {
                return ResourceManager.GetString("DE_ERROR_GEO_LONGITUDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Werte außerhalb des definierten Bereichs im WGS84 Datum: 
        ///Länge: -180 bis +180 E; Breite: -80 bis +84 N..
        /// </summary>
        internal static string DE_ERROR_GEO2UTM {
            get {
                return ResourceManager.GetString("DE_ERROR_GEO2UTM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Werte außerhalb des für Deutschland definierten Gauss-Krüger-Systems: 
        ///Länge: 5 bis 16 E; Breite: 46 bis 55 N..
        /// </summary>
        internal static string DE_ERROR_GK_OUT_OF_RANGE {
            get {
                return ResourceManager.GetString("DE_ERROR_GK_OUT_OF_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültiger interner Schlüssel für das Satellitenbild..
        /// </summary>
        internal static string DE_ERROR_MAPDIMENSION {
            get {
                return ResourceManager.GetString("DE_ERROR_MAPDIMENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format des MGRS-Koordinatenstrings konnte nicht erkannt werden oder außerhalb des gültigen Bereichs..
        /// </summary>
        internal static string DE_ERROR_MGRS {
            get {
                return ResourceManager.GetString("DE_ERROR_MGRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to East-Wert ungültig. .
        /// </summary>
        internal static string DE_ERROR_MGRS_EAST {
            get {
                return ResourceManager.GetString("DE_ERROR_MGRS_EAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid-Wert ungültig. Er besteht aus 2 Buchstaben..
        /// </summary>
        internal static string DE_ERROR_MGRS_GRID {
            get {
                return ResourceManager.GetString("DE_ERROR_MGRS_GRID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North-Wert ungültig..
        /// </summary>
        internal static string DE_ERROR_MGRS_NORTH {
            get {
                return ResourceManager.GetString("DE_ERROR_MGRS_NORTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültige Werte in dem von MapServiceTileBase abgeleiteten Parameter..
        /// </summary>
        internal static string DE_ERROR_TILE {
            get {
                return ResourceManager.GetString("DE_ERROR_TILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Band ungültig. Definierter Bereich: C bis X (ohne I und O)..
        /// </summary>
        internal static string DE_ERROR_UTM_BAND {
            get {
                return ResourceManager.GetString("DE_ERROR_UTM_BAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to East-Wert ungültig. Definierter Bereich: ca. 200000 bis 800000.
        /// </summary>
        internal static string DE_ERROR_UTM_EAST {
            get {
                return ResourceManager.GetString("DE_ERROR_UTM_EAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nord-Wert ungültig. Def.-Bereich: ca. 0 bis 9300000 (Nord), ca. 1100000 bis 10000000 (Süd).
        /// </summary>
        internal static string DE_ERROR_UTM_NORTH {
            get {
                return ResourceManager.GetString("DE_ERROR_UTM_NORTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der UTM-String konnte nicht erkannt werden (Format unbekannt)..
        /// </summary>
        internal static string DE_ERROR_UTM_STRING {
            get {
                return ResourceManager.GetString("DE_ERROR_UTM_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1} ist eine ungültige UTM-Zone..
        /// </summary>
        internal static string DE_ERROR_UTM_ZONE {
            get {
                return ResourceManager.GetString("DE_ERROR_UTM_ZONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone ungültig. Definierter Bereich: 1 bis 60..
        /// </summary>
        internal static string DE_ERROR_UTM_ZONE2 {
            get {
                return ResourceManager.GetString("DE_ERROR_UTM_ZONE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechts: {0}; Hoch: {1}.
        /// </summary>
        internal static string DE_GAUSS_LONG_STRING {
            get {
                return ResourceManager.GetString("DE_GAUSS_LONG_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R: {0}   H: {1}.
        /// </summary>
        internal static string DE_GAUSS_SHORT_STRING {
            get {
                return ResourceManager.GetString("DE_GAUSS_SHORT_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Länge: {0}; Breite: {1}.
        /// </summary>
        internal static string DE_GEOGRAPHIC_STRING {
            get {
                return ResourceManager.GetString("DE_GEOGRAPHIC_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satellitenbild in dieser Zoomstufe nicht verfügar..
        /// </summary>
        internal static string DE_MS_NO_IMAGE {
            get {
                return ResourceManager.GetString("DE_MS_NO_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nähere Angaben zum Fehler sind nicht verfügbar..
        /// </summary>
        internal static string DE_NO_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("DE_NO_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type conversion between {0} and {1} is not allowed..
        /// </summary>
        internal static string ERROR_CONVERTFROM {
            get {
                return ResourceManager.GetString("ERROR_CONVERTFROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to East value out of range for the german Gauss-Krueger-System: 
        ///Longitude: 5 bis 16 E..
        /// </summary>
        internal static string ERROR_GAUSS_EAST {
            get {
                return ResourceManager.GetString("ERROR_GAUSS_EAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North value out of range for the german Gauss-Krueger-System: 
        ///Latitude: 46 to 55 N..
        /// </summary>
        internal static string ERROR_GAUSS_NORTH {
            get {
                return ResourceManager.GetString("ERROR_GAUSS_NORTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude invalid. Range: -80 (South) to +84 (North).
        /// </summary>
        internal static string ERROR_GEO_LATITUDE {
            get {
                return ResourceManager.GetString("ERROR_GEO_LATITUDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude invalid. Range: -180 (West) to +180 (East).
        /// </summary>
        internal static string ERROR_GEO_LONGITUDE {
            get {
                return ResourceManager.GetString("ERROR_GEO_LONGITUDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values out of range for UTM: 
        ///Longitude: -180 to +180 E; Latitude: -80 to +84 N..
        /// </summary>
        internal static string ERROR_GEO2UTM {
            get {
                return ResourceManager.GetString("ERROR_GEO2UTM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values out of range for the german Gauss-Krueger-System: 
        ///Longitude: 5 bis 16 E; Latitude: 46 to 55 N..
        /// </summary>
        internal static string ERROR_GK_OUT_OF_RANGE {
            get {
                return ResourceManager.GetString("ERROR_GK_OUT_OF_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid internal key for the satellite picture..
        /// </summary>
        internal static string ERROR_MAPDIMENSION {
            get {
                return ResourceManager.GetString("ERROR_MAPDIMENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format of the MGRS string could not be parsed or out of range..
        /// </summary>
        internal static string ERROR_MGRS {
            get {
                return ResourceManager.GetString("ERROR_MGRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to East value invalid..
        /// </summary>
        internal static string ERROR_MGRS_EAST {
            get {
                return ResourceManager.GetString("ERROR_MGRS_EAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid value invalid. It needs 2 letters..
        /// </summary>
        internal static string ERROR_MGRS_GRID {
            get {
                return ResourceManager.GetString("ERROR_MGRS_GRID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North value invalid..
        /// </summary>
        internal static string ERROR_MGRS_NORTH {
            get {
                return ResourceManager.GetString("ERROR_MGRS_NORTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your MapServiceTileBase derived object contains invalid values..
        /// </summary>
        internal static string ERROR_TILE {
            get {
                return ResourceManager.GetString("ERROR_TILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Band invalid. Range: C to X (without I and O)..
        /// </summary>
        internal static string ERROR_UTM_BAND {
            get {
                return ResourceManager.GetString("ERROR_UTM_BAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to East value invalid. Range: approx. 200000 to 800000.
        /// </summary>
        internal static string ERROR_UTM_EAST {
            get {
                return ResourceManager.GetString("ERROR_UTM_EAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North value invalid. Range: approx. 0 to 9300000 (North), approx. 1100000 to 10000000 (South).
        /// </summary>
        internal static string ERROR_UTM_NORTH {
            get {
                return ResourceManager.GetString("ERROR_UTM_NORTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTM string could not be parsed (format unknown)..
        /// </summary>
        internal static string ERROR_UTM_STRING {
            get {
                return ResourceManager.GetString("ERROR_UTM_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1} is an invalid utm zone..
        /// </summary>
        internal static string ERROR_UTM_ZONE {
            get {
                return ResourceManager.GetString("ERROR_UTM_ZONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone invalid. Range: 1 to 60..
        /// </summary>
        internal static string ERROR_UTM_ZONE2 {
            get {
                return ResourceManager.GetString("ERROR_UTM_ZONE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to East: {0}; North: {1}.
        /// </summary>
        internal static string GAUSS_LONG_STRING {
            get {
                return ResourceManager.GetString("GAUSS_LONG_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E {0}   N {1}.
        /// </summary>
        internal static string GAUSS_SHORT_STRING {
            get {
                return ResourceManager.GetString("GAUSS_SHORT_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude: {0}; Latitude: {1}.
        /// </summary>
        internal static string GEOGRAPHIC_STRING {
            get {
                return ResourceManager.GetString("GEOGRAPHIC_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satellite picture with this zoom level not available ..
        /// </summary>
        internal static string MS_NO_IMAGE {
            get {
                return ResourceManager.GetString("MS_NO_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no error details available..
        /// </summary>
        internal static string NO_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("NO_ERROR_MESSAGE", resourceCulture);
            }
        }
    }
}
